language: android
jdk: oraclejdk8

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/
 
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-26
    #- sys-img-armeabi-v7a-android-17
	- tools
    
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
    - yes | sdkmanager "platforms;android-27"
	
script:
  # The build script to create a clean build with instrumentation test with no predexing and  stacktrace for errors
	# More about predexing and CI performance https://www.littlerobots.nl/blog/disable-android-pre-dexing-on-ci-builds/
  - ./gradlew clean build test check -PdisablePreDex --stacktrace
